tests: Add test cases for ignoring unsigned files
Add test cases covering the cases of a symlink and an additional file
created after a signature was created. Test expected failures and
passes with and without the new option --ignore_unsigned_files.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/scripts/tests/test-sign-verify b/scripts/tests/test-sign-verify
--- a/scripts/tests/test-sign-verify
+++ b/scripts/tests/test-sign-verify
@@ -160,6 +160,40 @@ fi
 check_model_name "${sigfile}" "$(basename "${TMPDIR}")"
 
 echo
+echo "Creating a symlink, that is not part of the signature, to make signature verification fail (1)"
+
+echo "foo" > symlinked
+ln -s symlinked symlink
+
+if python -m model_signing \
+	verify certificate \
+	--signature "$(basename "${sigfile}")" \
+	--certificate_chain "${DIR}/keys/certificate/ca-cert.pem" \
+	--ignore-paths "$(basename "${ignorefile}")" \
+	. ; then
+	echo "Error: 'verify certificate' succeeded after new file (symlink) was created"
+	exit 1
+fi
+
+# This should pass when passing --allow_symlinks when hashing all the files
+echo
+echo "Pass signature verification by ignoring any unsigned files or symlinks"
+if ! python -m model_signing \
+	verify certificate \
+	--signature "$(basename "${sigfile}")" \
+	--certificate_chain "${DIR}/keys/certificate/ca-cert.pem" \
+	--ignore-paths "$(basename "${ignorefile}")" \
+	--ignore_unsigned_files \
+	--allow_symlinks \
+	. ; then
+	echo "Error: 'verify certificate' failed with --ignore_unsigned_files while passing --allow_symlinks"
+	exit 1
+fi
+
+
+rm -f symlinked symlink
+
+echo
 echo "Testing 'sign/verify' certificate when in subdir of model directory and using '..'"
 
 rm -f "$(basename "${sigfile}")"
@@ -207,5 +241,72 @@ if [ "${res}" != "${exp}" ]; then
 	exit 1
 fi
 check_model_name "${sigfile}" "$(basename "${TMPDIR}")"
+
+echo
+echo "Creating a symlink, that is not part of the signature, to make signature verification fail (2)"
+
+# Create another symlinked file
+ln -s subdir/symlinked symlink2
+
+echo
+echo "Fail signature verification by NOT ignoring any unsigned (symlinks)"
+if python -m model_signing \
+	verify certificate \
+	--signature "$(basename "${sigfile}")" \
+	--certificate_chain "${DIR}/keys/certificate/ca-cert.pem" \
+	--ignore-paths "$(basename "${ignorefile}")" \
+	--allow_symlinks \
+	. ; then
+	echo "Error: 'verify certificate' succeeded after new file (symlink) was created"
+	exit 1
+fi
+
+echo
+echo "Pass signature verification by ignoring any unsigned files"
+if ! python -m model_signing \
+	verify certificate \
+	--signature "$(basename "${sigfile}")" \
+	--certificate_chain "${DIR}/keys/certificate/ca-cert.pem" \
+	--ignore-paths "$(basename "${ignorefile}")" \
+	--allow_symlinks \
+	--ignore_unsigned_files \
+	. ; then
+	echo "Error: 'verify certificate' failed with --ignore_unsigned_files to ignore symlink"
+	exit 1
+fi
+
+rm symlink2
+
+# Create a simple new file
+echo
+echo "Creating a regular file that is not part of the signature"
+touch newfile
+
+echo
+echo "Fail signature verification by NOT ignoring any unsigned files (symlinks)"
+if python -m model_signing \
+	verify certificate \
+	--signature "$(basename "${sigfile}")" \
+	--certificate_chain "${DIR}/keys/certificate/ca-cert.pem" \
+	--ignore-paths "$(basename "${ignorefile}")" \
+	--allow_symlinks \
+	. ; then
+	echo "Error: 'verify certificate' succeeded after new file was created"
+	exit 1
+fi
+
+echo
+echo "Pass signature verification by ignoring any unsigned files"
+if ! python -m model_signing \
+	verify certificate \
+	--signature "$(basename "${sigfile}")" \
+	--certificate_chain "${DIR}/keys/certificate/ca-cert.pem" \
+	--ignore-paths "$(basename "${ignorefile}")" \
+	--allow_symlinks \
+	--ignore_unsigned_files \
+	. ; then
+	echo "Error: 'verify certificate' failed with --ignore_unsigned_files to ignore regular file"
+	exit 1
+fi
 
 popd 1>/dev/null || exit 1
